organization: pq-code-package
repositories:
  - name: .github
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: documentation
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: mlkem-native
    teams:
      bots: admin
      pqcp-mlkem-native-admin: admin
      pqcp-mlkem-native-contributors: write
      pqcp-tsc: read
  - name: mldsa-native
    teams:
      bots: admin
      pqcp-mldsa-native-admin: admin
      pqcp-mldsa-native-contributors: write
      pqcp-tsc: read
  - name: slhdsa-c
    teams:
      bots: admin
      pqcp-slhdsa-c-admin: admin
      pqcp-slhdsa-c-contributors: write
      pqcp-tsc: read
  - name: mlkem-c-embedded
    teams:
      pqcp-embedded: read
      pqcp-embedded-admin: admin
      pqcp-embedded-maintainers: maintain
      pqcp-tsc: read
  - name: mlkem-c-generic
    teams:
      pqcp-generic-maintainers: maintain
      pqcp-generic-admin: admin
      pqcp-generic: read
      pqcp-tsc: read
  - name: mlkem-libjade
    teams:
      pqcp-libjade-admin: admin
      pqcp-libjade-maintainers: maintain
      pqcp-libjade: read
      pqcp-tsc: read
  - name: rust-libcrux
    teams:
      pqcp-libcrux: read
      pqcp-libcrux-admin: admin
      pqcp-libcrux-maintainers: maintain
      pqcp-tsc: read
  - name: pq-code-package-hackathon
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: template-code
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: tsc
    teams:
      pqcp-tsc: maintain
      pqcp-tsc-admin: admin
teams:
  - name: bots
    maintainers:
      - oqs-bot
  - name: pqcp-embedded-admin
    maintainers:
      - mkannwischer
  - name: pqcp-embedded-maintainers
    maintainers:
      - mkannwischer
    members:
      - rpls
      - potsrevennil
  - name: pqcp-embedded
    maintainers:
      - mkannwischer
    members:
      - cryptojedi
      - rpls
      - potsrevennil
      - jschanck
  - name: pqcp-mlkem-native-admin
    maintainers:
      - mkannwischer
      - hanno-becker
  - name: pqcp-mlkem-native-contributors
    maintainers:
      - mkannwischer
      - hanno-becker
    members:
      - cothan
      - potsrevennil
      - rod-chapman
      - jargh
      - dkostic
      - willieyz
      - mjosaarinen
      - bremoran
      - L-series
      - f15hr
  - name: pqcp-mldsa-native-admin
    maintainers:
      - mkannwischer
      - hanno-becker
    members:
      - jakemas
  - name: pqcp-mldsa-native-contributors
    maintainers:
      - mkannwischer
      - hanno-becker
    members:
      - potsrevennil
      - rod-chapman
      - jargh
      - dkostic
      - manastasova
      - willieyz
      - mjosaarinen
      - jammychiou1
      - bremoran
      - L-series
      - f15hr
  - name: pqcp-slhdsa-c-admin
    maintainers:
      - mkannwischer
    members:
      - mjosaarinen
      - praveksharma
      - dstebila
  - name: pqcp-slhdsa-c-contributors
    maintainers:
      - mkannwischer
      - mjosaarinen
      - praveksharma
      - dstebila
    members:
      - h2parson
      - willieyz
  - name: pqcp-generic-admin
    maintainers:
      - jschanck
    members:
      - cryptojedi
  - name: pqcp-generic-maintainers
    maintainers:
      - jschanck
    members:
      - cryptojedi
  - name: pqcp-generic
    maintainers:
      - jschanck
    members:
      - cryptojedi
      - ashman-p
  - name: pqcp-libcrux-admin
    maintainers:
      - franziskuskiefer
  - name: pqcp-libcrux-maintainers
    maintainers:
      - franziskuskiefer
    members:
  - name: pqcp-libcrux
    maintainers:
      - franziskuskiefer
    members:
      - karthikbhargavan
  - name: pqcp-libjade-admin
    maintainers:
      - mbbarbosa
    members:
      - cryptojedi
  - name: pqcp-libjade-maintainers
    maintainers:
      - mbbarbosa
    members:
      - cryptojedi
      - tfaoliveira
  - name: pqcp-libjade
    maintainers:
      - mbbarbosa
    members:
      - MQuaresma
      - cryptojedi
      - tfaoliveira
  - name: pqcp-docs
    maintainers:
      - mkannwischer
  - name: pqcp-docs-maintainers
    maintainers:
      - mkannwischer
  - name: pqcp-docs-admin
    maintainers:
      - mkannwischer
  - name: pqcp-tsc
    maintainers:
      - mkannwischer
    members:
      - mbbarbosa
      - hanno-becker
      - franziskuskiefer
      - jakemas
      - mjosaarinen
      - tfaoliveira
      - praveksharma
  - name: pqcp-tsc-admin
    maintainers:
      - mkannwischer
