organization: pq-code-package
repositories:
  - name: .github
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: documentation
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: mlkem-native
    teams:
      bots: admin
      pqcp-mlkem-native-admin: admin
      pqcp-mlkem-native-contributors: write
      pqcp-tsc: read
  - name: mldsa-native
    teams:
      bots: admin
      pqcp-mldsa-native-admin: admin
      pqcp-mldsa-native-contributors: write
      pqcp-tsc: read
  - name: mlkem-c-embedded
    teams:
      pqcp-embedded: read
      pqcp-embedded-admin: admin
      pqcp-embedded-maintainers: maintain
      pqcp-tsc: read
  - name: mlkem-c-generic
    teams:
      pqcp-generic-maintainers: maintain
      pqcp-generic-admin: admin
      pqcp-generic: read
      pqcp-tsc: read
  - name: mlkem-libjade
    teams:
      pqcp-libjade-admin: admin
      pqcp-libjade-maintainers: maintain
      pqcp-libjade: read
      pqcp-tsc: read
  - name: mlkem-rust-libcrux
    teams:
      pqcp-libcrux: read
      pqcp-libcrux-admin: admin
      pqcp-libcrux-maintainers: maintain
      pqcp-tsc: read
  - name: pq-code-package-hackathon
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: template-code
    teams:
      pqcp-docs: read
      pqcp-docs-maintainers: maintain
      pqcp-docs-admin: admin
      pqcp-tsc: read
  - name: tsc
    teams:
      pqcp-tsc: read
      pqcp-tsc-maintainers: maintain
      pqcp-tsc-admin: admin
teams:
  - name: bots
    maintainers:
      - oqs-bot
  - name: pqcp-contributors
    maintainers:
      - mkannwischer
      - planetf1
      - dstebila
    members:
      - hartm
      - rpls
      - MQuaresma
      - ajbozarth
      - cryptojedi
      - franziskuskiefer
      - jschanck
      - karthikbhargavan
      - mbbarbosa
      - potsrevennil
      - tfaoliveira
      - ashman-p
      - ydoroz
      - rod-chapman
      - praveksharma
      - jargh
      - dkostic
      - jakemas
      - manastasova
      - willieyz
      - mjosaarinen
  - name: pqcp-embedded-admin
    maintainers:
      - mkannwischer
      - planetf1
  - name: pqcp-embedded-maintainers
    maintainers:
      - mkannwischer
      - planetf1
    members:
      - rpls
      - potsrevennil
  - name: pqcp-embedded
    maintainers:
      - mkannwischer
      - planetf1
    members:
      - cryptojedi
      - rpls
      - potsrevennil
      - jschanck
  - name: pqcp-mlkem-native-admin
    maintainers:
      - mkannwischer
      - planetf1
      - hanno-becker
  - name: pqcp-mlkem-native-contributors
    maintainers:
      - mkannwischer
      - hanno-becker
    members:
      - cothan
      - potsrevennil
      - rod-chapman
      - jargh
      - dkostic
      - willieyz
      - mjosaarinen
  - name: pqcp-mldsa-native-admin
    maintainers:
      - mkannwischer
      - hanno-becker
    members:
      - jakemas
  - name: pqcp-mldsa-native-contributors
    maintainers:
      - mkannwischer
      - hanno-becker
    members:
      - potsrevennil
      - rod-chapman
      - jargh
      - dkostic
      - manastasova
      - willieyz
      - mjosaarinen
  - name: pqcp-generic-admin
    maintainers:
      - jschanck
      - planetf1
    members:
      - cryptojedi
  - name: pqcp-generic-maintainers
    maintainers:
      - planetf1
      - jschanck
    members:
      - cryptojedi
  - name: pqcp-generic
    maintainers:
      - planetf1
      - jschanck
    members:
      - cryptojedi
      - ashman-p
  - name: pqcp-libcrux-admin
    maintainers:
      - franziskuskiefer
      - planetf1
  - name: pqcp-libcrux-maintainers
    maintainers:
      - franziskuskiefer
      - planetf1
    members:
  - name: pqcp-libcrux
    maintainers:
      - franziskuskiefer
      - planetf1
    members:
      - karthikbhargavan
  - name: pqcp-libjade-admin
    maintainers:
      - planetf1
    members:
      - cryptojedi
  - name: pqcp-libjade-maintainers
    maintainers:
      - planetf1
    members:
      - cryptojedi
      - mbbarbosa
      - tfaoliveira
  - name: pqcp-libjade
    maintainers:
      - mbbarbosa
      - planetf1
    members:
      - MQuaresma
      - cryptojedi
      - tfaoliveira
  - name: pqcp-docs
    maintainers:
      - planetf1
  - name: pqcp-docs-maintainers
    maintainers:
      - planetf1
  - name: pqcp-docs-admin
    maintainers:
      - planetf1
  - name: pqcp-tsc
    maintainers:
      - planetf1
    members:
      - MQuaresma
      - ajbozarth
      - ashman-p
      - cryptojedi
      - franziskuskiefer
      - hanno-becker
      - jschanck
      - karthikbhargavan
      - mbbarbosa
      - mkannwischer
      - potsrevennil
      - rpls
      - tfaoliveira
      - praveksharma
      - jakemas
  - name: pqcp-tsc-maintainers
    maintainers:
      - planetf1
    members:
      - franziskuskiefer
      - hanno-becker
      - jschanck
      - mbbarbosa
      - mkannwischer
      - tfaoliveira
      - praveksharma
      - jakemas
  - name: pqcp-tsc-admin
    maintainers:
      - planetf1
